language: java
jdk:
  - openjdk8
sudo: required
branches:
  only:
    - master
notifications:
  email:
    - sumusb34@gmail.com
  on_success: always
  on_failure: always
env:
  - TAG="$(git rev-parse --short HEAD)"
script:
  - ./gradlew booJar
  - docker build .
  - echo $TAG
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
  - docker push iljun/travis-docker:${TRAVIS_COMMIT}