language: java
jdk:
  - openjdk8
sudo: required
services:
  - docker
branches:
  only:
    - master
env:
  - TAG="$(git rev-parse --short HEAD)"
notifications:
  email:
    - sumusb34@gmail.com
  on_success: always
  on_failure: always
before_script:
  - sudo docker pull registry:latest
script:
  - ./gradlew booJar
  - docker build -t wepet-docker-registry/travis-docker:${TAG} .
  - sudo docker run -d -p 5000:5000 --name s3-registry \
    -e SETTINGS_FLAVOR=s3 \
    -e AWS_BUCKET=wepet-docker-registry \
    -e STORAGE_PATH=/registry \
    -e AWS_KEY=${S3_ACCESS_KEY} \
    -e AWS_SECRET=${S3_SECRET} \
    registry
  - sudo docker push localhost:5000/travis-docker:${TAG}
