language: java
jdk:
  - openjdk8
sudo: required
services:
  - docker
branches:
  only:
    - master
env:
  - TAG="$(git rev-parse --short HEAD)"
notifications:
  email:
    - sumusb34@gmail.com
  on_success: always
  on_failure: always
before_script:
  - sudo docker pull registry:latest
script:
  - ./gradlew booJar
  - echo ${TAG}
  - echo TAG
  - echo "${TAG}"
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region ap-northeast-2)
  - docker build -t 989243724240.dkr.ecr.ap-northeast-2.amazonaws.com/wepet:${TAG} .
  - docker push 989243724240.dkr.ecr.ap-northeast-2.amazonaws.com/wepet:${TAG}
