language: java
jdk:
  - openjdk8
sudo: required
services:
  - docker
branches:
  only:
    - master
env:
  - TAG="$(git rev-parse --short HEAD)"
notifications:
  email:
    - sumusb34@gmail.com
  on_success: always
  on_failure: always
script:
  - ./gradlew booJar
  - docker build -t wepet-docker-registry/travis-docker:${TAG} .
deploy:
  provider: s3
  access_key_id: ${S3_ACCESS_KEY}
  secret_access_key: ${S3_SECRET}
  bucket: "wepet-docker-registry"
